/**
 * Querium — Phase 6: migration autogeneration.
 *
 * Turns a diff's `Operation[]` into an editable TypeScript migration file with
 * `up()` and an autogenerated, inverted `down()`. Operations are embedded as
 * plain-data literals (they are JSON-serializable), so the file stays readable
 * and hand-editable — never an opaque `.sql` blob.
 */

import { type Operation, invertAll } from "./operations.js";

/** Inputs for one generated migration file. */
export interface MigrationDraft {
  readonly revision: string;
  readonly downRevision: readonly string[];
  readonly label: string;
  readonly operations: readonly Operation[];
}

/** Serialize operations as an indented array literal for the generated file. */
function renderOps(ops: readonly Operation[]): string {
  if (ops.length === 0) return "[]";
  const body = ops.map((op) => `    ${JSON.stringify(op)},`).join("\n");
  return `[\n${body}\n  ]`;
}

/**
 * Render a migration file body as TypeScript source.
 *
 * The generated `down()` inverts `up()`; if any operation is irreversible, the
 * generation still succeeds but `down()` throws at run time with a clear message
 * (so reversibility is never silently broken).
 *
 * @param draft The revision id, parents, label, and forward operations.
 * @returns The migration file source.
 */
export function generateMigration(draft: MigrationDraft): string {
  let down: string;
  try {
    down = renderOps(invertAll(draft.operations));
  } catch (error) {
    down = `(() => { throw new Error(${JSON.stringify(
      `irreversible migration: ${(error as Error).message}`,
    )}); })()`;
  }

  return `import type { Migration, Op } from "querium/migrations";

export const revision = ${JSON.stringify(draft.revision)};
export const downRevision: string[] = ${JSON.stringify(draft.downRevision)};
export const label = ${JSON.stringify(draft.label)};

const upOps = ${renderOps(draft.operations)};

const downOps = ${down};

export const up = (op: Op): void => {
  for (const operation of upOps) op.run(operation);
};

export const down = (op: Op): void => {
  for (const operation of downOps) op.run(operation);
};

export default { revision, downRevision, label, up, down } satisfies Migration;
`;
}

/** Build a short, stable revision id from a label + parent set. */
export function makeRevisionId(label: string, parents: readonly string[]): string {
  // Deterministic non-crypto hash (FNV-1a) — no Date/Math.random (build-stable).
  let hash = 0x811c9dc5;
  for (const ch of `${label}|${[...parents].sort().join(",")}`) {
    hash ^= ch.charCodeAt(0);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, "0");
}
