/**
 * tempest-db-js — Phase 6: typed migration operations.
 *
 * Every schema change is a typed `Operation` with a known inverse. This is what
 * gives autogenerated, reversible `down()` and dialect-rendered DDL — never a
 * hand-written `.sql` blob (the anti-Drizzle core).
 */

import type { ColumnIR, NamedConstraint, TableIR } from "./ir.js";

/** A single, reversible schema operation. */
export type Operation =
  | { readonly kind: "create_table"; readonly table: TableIR }
  | { readonly kind: "drop_table"; readonly table: TableIR }
  | { readonly kind: "rename_table"; readonly from: string; readonly to: string }
  | { readonly kind: "add_column"; readonly table: string; readonly column: ColumnIR }
  | { readonly kind: "drop_column"; readonly table: string; readonly column: ColumnIR }
  | {
      readonly kind: "alter_column";
      readonly table: string;
      readonly name: string;
      readonly from: ColumnIR;
      readonly to: ColumnIR;
    }
  | {
      readonly kind: "rename_column";
      readonly table: string;
      readonly from: string;
      readonly to: string;
    }
  | {
      // Rebuild a table from `from` to `to`. On SQLite this is the batch /
      // table-rebuild path (SQLite cannot ALTER COLUMN); on PostgreSQL it is
      // realized as per-column ALTER/ADD/DROP.
      readonly kind: "recreate_table";
      readonly from: TableIR;
      readonly to: TableIR;
    }
  | {
      // Add a table-level unique / foreign-key constraint. On SQLite this needs
      // a table-rebuild (recreate_table); PostgreSQL / MySQL use ALTER TABLE ADD.
      readonly kind: "add_constraint";
      readonly table: string;
      readonly constraint: NamedConstraint;
    }
  | {
      readonly kind: "drop_constraint";
      readonly table: string;
      readonly constraint: NamedConstraint;
    }
  | { readonly kind: "execute"; readonly up: string; readonly down: string | null };

/** Raised when an operation has no safe inverse (e.g. a one-way `execute`). */
export class IrreversibleMigration extends Error {
  constructor(message: string) {
    super(message);
    this.name = "IrreversibleMigration";
  }
}

/**
 * Compute the inverse of an operation, for autogenerated `down()`.
 *
 * @param op The forward operation.
 * @returns The operation that undoes it.
 * @throws IrreversibleMigration When `op` cannot be safely reversed.
 */
export function invert(op: Operation): Operation {
  switch (op.kind) {
    case "create_table":
      return { kind: "drop_table", table: op.table };
    case "drop_table":
      return { kind: "create_table", table: op.table };
    case "rename_table":
      return { kind: "rename_table", from: op.to, to: op.from };
    case "add_column":
      return { kind: "drop_column", table: op.table, column: op.column };
    case "drop_column":
      return { kind: "add_column", table: op.table, column: op.column };
    case "alter_column":
      return {
        kind: "alter_column",
        table: op.table,
        name: op.name,
        from: op.to,
        to: op.from,
      };
    case "rename_column":
      return { kind: "rename_column", table: op.table, from: op.to, to: op.from };
    case "recreate_table":
      return { kind: "recreate_table", from: op.to, to: op.from };
    case "add_constraint":
      return { kind: "drop_constraint", table: op.table, constraint: op.constraint };
    case "drop_constraint":
      return { kind: "add_constraint", table: op.table, constraint: op.constraint };
    case "execute":
      if (op.down === null) {
        throw new IrreversibleMigration("execute() operation has no down SQL");
      }
      return { kind: "execute", up: op.down, down: op.up };
  }
}

/** Invert a list of operations: reverse order, each inverted. */
export function invertAll(ops: readonly Operation[]): Operation[] {
  return [...ops].reverse().map(invert);
}
