/**
 * tempest-db-js — Phase 6: the migration runner.
 *
 * The `Op` facade records operations; the `MigrationRunner` renders them to SQL
 * (per dialect) and runs them through a sync driver, tracking applied revisions
 * in a `tempest_db_js_migrations` table. Upgrades/downgrades respect the revision DAG.
 *
 * SQLite execution is real (via `node:sqlite`); the same code path serves any
 * sync driver.
 */

import type { AsyncDriver, SyncDriver } from "../engine.js";
import type { Dialect } from "../url.js";
import { renderOperation } from "./ddl.js";
import { topoOrder } from "./graph.js";
import type { ColumnIR, TableIR } from "./ir.js";
import { type Operation, invertAll } from "./operations.js";

/**
 * The facade injected into `up()`/`down()`. Each method records an operation;
 * the runner renders and executes them after the function returns.
 */
export class Op {
  readonly operations: Operation[] = [];

  /** Record a raw operation (used by autogenerated migrations). */
  run(operation: Operation): void {
    this.operations.push(operation);
  }

  createTable(table: TableIR): void {
    this.run({ kind: "create_table", table });
  }
  dropTable(table: TableIR): void {
    this.run({ kind: "drop_table", table });
  }
  renameTable(from: string, to: string): void {
    this.run({ kind: "rename_table", from, to });
  }
  addColumn(table: string, column: ColumnIR): void {
    this.run({ kind: "add_column", table, column });
  }
  dropColumn(table: string, column: ColumnIR): void {
    this.run({ kind: "drop_column", table, column });
  }
  alterColumn(table: string, name: string, from: ColumnIR, to: ColumnIR): void {
    this.run({ kind: "alter_column", table, name, from, to });
  }
  renameColumn(table: string, from: string, to: string): void {
    this.run({ kind: "rename_column", table, from, to });
  }
  /** Rebuild a table (SQLite batch-mode / PostgreSQL per-column alters). */
  recreateTable(from: TableIR, to: TableIR): void {
    this.run({ kind: "recreate_table", from, to });
  }
  /** Raw SQL escape hatch (e.g. a data migration). `down` may be `null`. */
  execute(up: string, down: string | null = null): void {
    this.run({ kind: "execute", up, down });
  }
}

/** A migration file's shape. */
export interface Migration {
  readonly revision: string;
  readonly downRevision: readonly string[];
  readonly label?: string;
  up(op: Op): void;
  down(op: Op): void;
}

const VERSION_TABLE = "tempest_db_js_migrations";

/** Runs migrations against a sync driver, tracking applied revisions. */
export class MigrationRunner {
  constructor(
    private readonly driver: SyncDriver,
    private readonly dialect: Dialect,
  ) {}

  /** Create the version-tracking table if it does not exist. */
  ensureVersionTable(): void {
    this.driver.execute(
      `CREATE TABLE IF NOT EXISTS "${VERSION_TABLE}" (revision TEXT PRIMARY KEY, applied_at TEXT NOT NULL, down_revision TEXT NOT NULL)`,
      [],
    );
  }

  /** The set of applied revision ids. */
  applied(): Set<string> {
    this.ensureVersionTable();
    const { rows } = this.driver.execute(`SELECT revision FROM "${VERSION_TABLE}"`, []);
    return new Set(rows.map((r) => String(r.revision)));
  }

  private runOps(ops: readonly Operation[]): void {
    for (const op of ops) {
      for (const stmt of renderOperation(op, this.dialect)) {
        const trimmed = stmt.trim();
        if (trimmed.length === 0 || trimmed.startsWith("--")) continue;
        this.driver.execute(stmt, []);
      }
    }
  }

  private record(migration: Migration, appliedAt: string): void {
    this.driver.execute(
      `INSERT INTO "${VERSION_TABLE}" (revision, applied_at, down_revision) VALUES (?, ?, ?)`,
      [migration.revision, appliedAt, migration.downRevision.join(",")],
    );
  }

  private forget(revision: string): void {
    this.driver.execute(`DELETE FROM "${VERSION_TABLE}" WHERE revision = ?`, [revision]);
  }

  /**
   * Apply all pending migrations up to the head(s), in DAG order.
   *
   * @param migrations All known migrations.
   * @param appliedAt Timestamp string to stamp (pass one in — the runtime has no
   *   wall clock of its own here).
   * @returns The revision ids that were applied this run.
   */
  upgrade(migrations: readonly Migration[], appliedAt: string): string[] {
    const done = this.applied();
    const ordered = topoOrder(migrations);
    const ran: string[] = [];
    for (const migration of ordered) {
      if (done.has(migration.revision)) continue;
      const op = new Op();
      migration.up(op);
      this.runOps(op.operations);
      this.record(migration, appliedAt);
      ran.push(migration.revision);
    }
    return ran;
  }

  /**
   * Revert the last `steps` applied migrations (default 1), newest first.
   *
   * @param migrations All known migrations.
   * @param steps How many applied revisions to roll back.
   * @returns The revision ids that were reverted.
   */
  downgrade(migrations: readonly Migration[], steps = 1): string[] {
    const done = this.applied();
    const ordered = topoOrder(migrations).filter((m) => done.has(m.revision));
    const toRevert = ordered.slice(-steps).reverse();
    const reverted: string[] = [];
    for (const migration of toRevert) {
      const op = new Op();
      // Prefer the migration's own down(); fall back to inverting up().
      if (migration.down.length >= 0) {
        try {
          migration.down(op);
        } catch {
          op.operations.length = 0;
        }
      }
      if (op.operations.length === 0) {
        const upOp = new Op();
        migration.up(upOp);
        op.operations.push(...invertAll(upOp.operations));
      }
      this.runOps(op.operations);
      this.forget(migration.revision);
      reverted.push(migration.revision);
    }
    return reverted;
  }
}

// ---------------------------------------------------------------------------
// async runner (PostgreSQL / any async driver)
// ---------------------------------------------------------------------------

/** Quote an identifier for the dialect (backticks on MySQL, double-quotes else). */
function quoteIdent(name: string, dialect: Dialect): string {
  return dialect === "mysql"
    ? `\`${name.replace(/`/g, "``")}\``
    : `"${name.replace(/"/g, '""')}"`;
}

/** The n-th (1-based) placeholder for the dialect (`$n` on PostgreSQL, `?` else). */
function placeholder(index: number, dialect: Dialect): string {
  return dialect === "postgresql" ? `$${index}` : "?";
}

/**
 * Runs migrations against an **async** driver (PostgreSQL, or any async driver),
 * tracking applied revisions. Mirrors {@link MigrationRunner} but every statement
 * is awaited, and identifier quoting + placeholder style follow the dialect —
 * so the version table and its bookkeeping are portable across SQLite/PG/MySQL.
 */
export class AsyncMigrationRunner {
  private readonly vt: string;

  constructor(
    private readonly driver: AsyncDriver,
    private readonly dialect: Dialect,
  ) {
    this.vt = quoteIdent(VERSION_TABLE, dialect);
  }

  /** Create the version-tracking table if it does not exist. */
  async ensureVersionTable(): Promise<void> {
    await this.driver.execute(
      `CREATE TABLE IF NOT EXISTS ${this.vt} (revision ${this.textType()} PRIMARY KEY, applied_at ${this.textType()} NOT NULL, down_revision ${this.textType()} NOT NULL)`,
      [],
    );
  }

  /** A portable "text" column type for the version table. */
  private textType(): string {
    // MySQL cannot index an unbounded TEXT primary key; use VARCHAR there.
    return this.dialect === "mysql" ? "VARCHAR(255)" : "TEXT";
  }

  /** The set of applied revision ids. */
  async applied(): Promise<Set<string>> {
    await this.ensureVersionTable();
    const { rows } = await this.driver.execute(`SELECT revision FROM ${this.vt}`, []);
    return new Set(rows.map((r) => String(r.revision)));
  }

  private async runOps(ops: readonly Operation[]): Promise<void> {
    for (const op of ops) {
      for (const stmt of renderOperation(op, this.dialect)) {
        const trimmed = stmt.trim();
        if (trimmed.length === 0 || trimmed.startsWith("--")) continue;
        await this.driver.execute(stmt, []);
      }
    }
  }

  private async record(migration: Migration, appliedAt: string): Promise<void> {
    const p = (i: number) => placeholder(i, this.dialect);
    await this.driver.execute(
      `INSERT INTO ${this.vt} (revision, applied_at, down_revision) VALUES (${p(1)}, ${p(2)}, ${p(3)})`,
      [migration.revision, appliedAt, migration.downRevision.join(",")],
    );
  }

  private async forget(revision: string): Promise<void> {
    await this.driver.execute(
      `DELETE FROM ${this.vt} WHERE revision = ${placeholder(1, this.dialect)}`,
      [revision],
    );
  }

  /**
   * Apply all pending migrations up to the head(s), in DAG order.
   *
   * @param migrations All known migrations.
   * @param appliedAt Timestamp string to stamp on each applied revision.
   * @returns The revision ids that were applied this run.
   */
  async upgrade(migrations: readonly Migration[], appliedAt: string): Promise<string[]> {
    const done = await this.applied();
    const ordered = topoOrder(migrations);
    const ran: string[] = [];
    for (const migration of ordered) {
      if (done.has(migration.revision)) continue;
      const op = new Op();
      migration.up(op);
      await this.runOps(op.operations);
      await this.record(migration, appliedAt);
      ran.push(migration.revision);
    }
    return ran;
  }

  /**
   * Revert the last `steps` applied migrations (default 1), newest first.
   *
   * @param migrations All known migrations.
   * @param steps How many applied revisions to roll back.
   * @returns The revision ids that were reverted.
   */
  async downgrade(migrations: readonly Migration[], steps = 1): Promise<string[]> {
    const done = await this.applied();
    const ordered = topoOrder(migrations).filter((m) => done.has(m.revision));
    const toRevert = ordered.slice(-steps).reverse();
    const reverted: string[] = [];
    for (const migration of toRevert) {
      const op = new Op();
      try {
        migration.down(op);
      } catch {
        op.operations.length = 0;
      }
      if (op.operations.length === 0) {
        const upOp = new Op();
        migration.up(upOp);
        op.operations.push(...invertAll(upOp.operations));
      }
      await this.runOps(op.operations);
      await this.forget(migration.revision);
      reverted.push(migration.revision);
    }
    return reverted;
  }
}
